import {attribute, autoGeneratedHashKey, table} from '@aws/dynamodb-data-mapper-annotations';
import {ApiModelProperty} from '@nestjs/swagger';
import {ExtendedEntity} from '../../_helpers';
import {IsString} from 'class-validator';

@table(`conversation`)
export class ConversationEntity extends ExtendedEntity {

	@ApiModelProperty()
	@autoGeneratedHashKey()
	public id: string;

	@ApiModelProperty()
	@attribute()
	public createdAt: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public homeId: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public type: string;
}
