import {attribute, autoGeneratedHashKey, table} from '@aws/dynamodb-data-mapper-annotations';
import {ApiModelProperty} from '@nestjs/swagger';
import {ExtendedEntity} from '../../_helpers';
import {IsString} from 'class-validator';
import {Column, Entity, ObjectIdColumn} from 'typeorm';

@Entity()
export class UserConversationEntity extends ExtendedEntity {

	@ApiModelProperty()
	@ObjectIdColumn()
	public id: string;

	@ApiModelProperty()
	@IsString()
	@Column()
	public conversationId: string;

	@ApiModelProperty()
	@IsString()
	@Column()
	public userId: string;
}
