import {ApiModelProperty} from '@nestjs/swagger';
import {
	autoGeneratedHashKey,
	versionAttribute,
	rangeKey, attribute
} from '@aws/dynamodb-data-mapper-annotations';
import {IsString} from 'class-validator';

export class ExtendedEntity {
	public id?: string;

	@ApiModelProperty()
	@attribute()
	public createdAt: string;

	@ApiModelProperty()
	@attribute()
	public updatedAt: string;
}
