import {IsOptional, IsEmail, IsString, MinLength, Validate} from 'class-validator';
import {ApiModelProperty} from '@nestjs/swagger';
import {
	table,
	attribute, autoGeneratedHashKey, versionAttribute, rangeKey
} from '@aws/dynamodb-data-mapper-annotations';
import {ExtendedEntity, passwordHash} from '../../_helpers';
import {IsUserAlreadyExist} from '../user.validator';
import {config} from '../../../config';

@table(`users`)
export class UserEntity extends ExtendedEntity {

	@ApiModelProperty()
	@autoGeneratedHashKey()
	public id: string;

	@ApiModelProperty()
	@attribute()
	public cratedAt: Date;

	@ApiModelProperty()
	@attribute()
	public updatedAt: Date;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public name: string;

	@ApiModelProperty()
	@IsEmail()
	/*@Validate(IsUserAlreadyExist, {
		message: 'User already exists'
	})*/
	@attribute()
	public email: string;

	@ApiModelProperty()
	@IsOptional()
	@attribute()
	public provider: string;

	@ApiModelProperty()
	@IsOptional()
	@attribute()
	public socialId: string;

	@ApiModelProperty()
	@MinLength(7)
	@IsOptional()
	@attribute()
	public password: string;

	hashPassword() {
		this.password = passwordHash(this.password);
	}
}
