import {attribute, autoGeneratedHashKey, table} from '@aws/dynamodb-data-mapper-annotations';
import {ApiModelProperty} from '@nestjs/swagger';
import {IsEmail, IsOptional, IsString, IsUrl, MinLength, Validate, ValidateIf} from 'class-validator';
import {ExtendedEntity, passwordHash} from '../../_helpers';
import {IsUserAlreadyExist} from '../user.validator';

@table(`users`)
export class UserEntity extends ExtendedEntity {

	@ApiModelProperty()
	@autoGeneratedHashKey()
	public id: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public first_name: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public last_name: string;

	@ApiModelProperty()
	@IsEmail()
	@ValidateIf(o => !o.id)
	@Validate(IsUserAlreadyExist, {
		message: 'User already exists'
	})
	@attribute()
	public email: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	public phone_num: string;

	@ApiModelProperty()
	@IsOptional()
	@IsUrl()
	@attribute()
	public profile_img: string;

	@ApiModelProperty()
	@MinLength(7)
	@IsOptional()
	@attribute()
	public password: string;

	@ApiModelProperty()
	@attribute()
	public is_verified = false;

	@ApiModelProperty()
	@IsOptional()
	@attribute()
	public provider: string;

	@ApiModelProperty()
	@IsOptional()
	@attribute()
	public socialId: string;

	@ApiModelProperty()
	@attribute()
	public createdAt: string;

	@ApiModelProperty()
	@attribute()
	public updatedAt: string;

	hashPassword() {
		this.password = passwordHash(this.password);
	}
}
