import {attribute, autoGeneratedHashKey, table} from '@aws/dynamodb-data-mapper-annotations';
import {ApiModelProperty} from '@nestjs/swagger';
import {IsNumber, IsString} from 'class-validator';

@table('home_media')
export class HomeMediaEntity {

	@ApiModelProperty()
	@autoGeneratedHashKey()
	id: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	homeId: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	originalname: string;

	@ApiModelProperty()
	@IsString()
	@attribute()
	mimetype: string;

	@ApiModelProperty()
	@IsNumber()
	@attribute()
	size: number;

	@ApiModelProperty()
	@IsString()
	@attribute()
	url: string;
}
